import Config

# Configure your database
config :repo_builder, RepoBuilder.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "repo_builder_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# In dev the default orchestrator runs on the keyless Fake harness so the console
# brain works end-to-end without a CLI or API key (§13).
config :repo_builder, :orchestrator, default_harness: "fake"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :repo_builder, RepoBuilderWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "LRN3TG8eIUPIKxjIlEqyEUba2HMKMxGRs8mCeIjqpXJWjPiTVpsvK2/xGwfcFScT",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:repo_builder, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:repo_builder, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :repo_builder, RepoBuilderWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/repo_builder_web/router\.ex$"E,
      ~r"lib/repo_builder_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :repo_builder, dev_routes: true

# Attach the LiveView perf telemetry handler in dev so mount/handle_event timing
# lines ([lv_perf] …) land in the server log (RepoBuilder.Telemetry.LiveViewPerf).
config :repo_builder, :lv_perf_handler, attach: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Per-project secrets vault master key for LOCAL DEV ONLY
# (issue-per-project-encrypted-secrets-vault). Base64 of 32 random bytes. This is a
# throwaway dev key so the vault works out of the box at http://localhost:4000 (deposit
# a secret, provision an external API). It is NOT a production secret — prod sources the
# key from the `SECRETS_KEY` OS env var in config/runtime.exs, which OVERRIDES this when
# set (the runtime.exs guard never clobbers it). Rotate or remove freely.
config :repo_builder, RepoBuilder.Secrets, key: "bl02HB0PGQHUMERy2XPtYOhMKpRB6E2IXs5am1Gqgaw="
